### ISSUE TITLE
Move Dinis to-do list from Confluence to GitHub

### ISSUE THREAD

**Issue by DinisCruz** [photobox/pbx-group-security#48]
http://confluence.photobox.com/display/SEC/Issues+for+Dinis+to+fix 

**Issues for Dinis to Fix**
- [x] Contact page gives 404
- [ ] Favicon won't update
- [x] Remove blog listing from footer
- [x] Identify what the random green box links are and where they are coming from and get rid (see under address in footer for example)
- [ ] Remove the requirement for images in testimonials - in chrome this is not shown, on safari I see a broken image icon
- [ ] Update social icons Photoboxgroup_mailLogo50pxRGB.png, Photoboxgroup_githubLogo50pxRGB.png, Photoboxgroup_twitterLogo50pxRGB.png
- [x] How do we update carousel banner and carousel item images? When I try it changes the item images to the one I'm trying to add to the banner

**Pages to check**
- [ ]  http://confluence.photobox.com/display/SEC/Pages+to+check

**Comment by DinisCruz** [comment]
@rajendira  can you create individual issues for the ones that are not done? (and mark them as bugs or content issues)

**Comment by Abhi-Raj** [comment]
other than the tasks listed here, are there any other tasks in org. confluence which we need to pull? -> http://confluence.photobox.com/display/SEC/Issues+for+Dinis+to+fix 

Currently, don't have access to the internal site

**Comment by JemmaDSmith** [comment]
Here is the list from the page:

Contact page gives 404
Favicon won't update
Remove blog listing from footer
Identify what the random green box links are and where they are coming from and get rid (see under address in footer for example)
Remove the requirement for images in testimonials - in chrome this is not shown, on safari I see a broken image icon
Update social icons Photoboxgroup_mailLogo50pxRGB.png, Photoboxgroup_githubLogo50pxRGB.png, Photoboxgroup_twitterLogo50pxRGB.png
How do we update carousel banner and carousel item images? When I try it changes the item images to the one I'm trying to add to the banner

**Comment by Abhi-Raj** [comment]
Multiple individual issues created from this issue. Closed.
